### ISSUE TITLE
Ability to Fake Active Directory

### ISSUE THREAD

**Issue by gbam** [swimlane/soc-faker#5]
Get a single user's information back from active directory.  Raw response outputs:
![image](https://user-images.githubusercontent.com/2936456/85798201-11d64600-b70b-11ea-8049-8f362d4fd7d6.png)

**Comment by MSAdministrator** [comment]
I believe all of this is available under the employee class.

e.g. SocFaker().employee

Closing out.

**Comment by joshswimlane** [comment]
I believe this is all available under the employee class.

e.g. SocFaker().employee

Closing out.
